entelai/urls.py
from django.views.generic import TemplateView
from django.conf.urls import include, url
"""entelai URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', TemplateView.as_view(template_name="index.html"),name='index'),
    url(r'^peliculas/', include('peliculas.urls'),name='peliculas'),
]

peliculas/urls.py
from django.conf.urls import url

from .views import *

app_name = 'peliculas'

urlpatterns = [
    url(r'upload-csv/', csv_upload, name="csv_upload"),
    url(r'costo-total/', costo_total, name="costo_total"),
    url(r'costo-promedio/', costo_promedio, name="costo_promedio"),

]

peliculas/models.py
from django.db import models

class Pelicula(models.Model):
    imdb_title_id = models.CharField(max_length=30, primary_key = True)
    title = models.CharField(max_length=100)
    original_title = models.CharField(max_length=100)
    year = models.IntegerField(blank=True,null=True)
    date_published = models.DateField(blank=True,null=True)
    genre = models.CharField(max_length=50)
    duration = models.IntegerField(blank=True,null=True)
    country = models.CharField(max_length=20)
    language = models.CharField(max_length=20)
    director = models.CharField(max_length=40)
    writer  = models.CharField(max_length=40)
    production_company = models.CharField(max_length=40)
    actors = models.CharField(max_length=100)
    description = models.CharField(max_length=100)
    avg_vote = models.CharField(max_length=100)
    votes = models.CharField(max_length=100)
    budget = models.CharField(max_length=100)
    usa_gross_income = models.CharField(max_length=100)
    worlwide_gross_income = models.CharField(max_length=100)
    metascore = models.CharField(max_length=100)
    reviews_from_users = models.CharField(max_length=100)
    reviews_from_critics = models.CharField(max_length=100)

peliculas/views.py
from django.shortcuts import render
from django.views import View
from django.http import HttpResponseRedirect
from django.http import JsonResponse
import pandas as pd
import re
from .models import Pelicula
# Create your views here.

def csv_upload(request):
    
    Pelicula.objects.all().delete() #Solo para este ejercicio, evitar errores de integridad

    csv_file = request.FILES['csv_file']

    df=pd.read_csv(csv_file,sep=',')
    df['year'] = df['year'].replace(to_replace=r'[A-Za-z]+.', value='', regex=True)
    df['date_published'] = df['date_published'].replace(to_replace=r'[A-Za-z]+.', value='', regex=True)
    df['date_published'] = pd.to_datetime(df['date_published'],errors='ignore', format="%Y/%d/%m",infer_datetime_format=True)
    df = df.fillna(0)
    
    peliculas = []
    for e in df.T.to_dict().values():
        peliculas.append(Pelicula(**e))

    Pelicula.objects.bulk_create(peliculas)
    
    return HttpResponseRedirect('/')

#http://127.0.0.1:8000/peliculas/costo-total/?pais=USA (o cualquier pais)
def costo_total(request):
    """costo total (budget) de todas las películas cuyo país es USA"""
    pais = request.GET.get('pais')
    peliculas = Pelicula.objects.all().filter(country=pais)
    costo_total = 0
    for p in peliculas: 
        costo_total += float(re.sub('[A-Z]|[\$].','', p.budget))
    
    return JsonResponse({"pais":pais,"costo-total": costo_total})

#http://localhost:8000/peliculas/costo-promedio/?pais=USA
def costo_promedio(request):
    """costo promedio por película de todas las películas cuyo país es USA"""
    pais = request.GET.get('pais')
    peliculas = Pelicula.objects.all().filter(country=pais).filter(budget__lt=0)  
    costo_total = 0
    costo_primedio = 0
    for p in peliculas: 
        costo_total += float(re.sub('[A-Z]|[\$].','', p.budget))
    costo_primedio = round(costo_total/len(peliculas),2)
    return JsonResponse({"pais":pais,"costo_primedio": costo_primedio})
    

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Entelai</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

</head>
<body>
    <h1>Carga de Base de Datos</h1>
    <form action="{% url "peliculas:csv_upload" %}" method="POST" enctype="multipart/form-data" class="form-horizontal"> 
        {% csrf_token %}
        <div class="form-group">
            <div class="col-md-8">
                <input type="file" name="csv_file" id="csv_file" required="True" class="form-control">
            </div>                    
        </div>
        <div class="form-group">                    
            <div class="col-md-3 col-sm-3 col-xs-12 col-md-offset-3" style="margin-bottom:10px;">
                 <button class="btn btn-primary"> <span class="glyphicon glyphicon-upload" style="margin-right:5px;"></span>Upload </button>
            </div> 
        </div>
    </form>
</body>
</html>